### ISSUE TITLE
Producer allows serializer to be added, but consumer does not

### ISSUE THREAD

**Issue by bbradbury** [joekiller/jruby-kafka#2]
Looks like there's no place to hook in a custom serializer in the consumer class.

I'd propose the ability to call one of the overrides of ConsumerConnector.createMessageStreams here:
https://github.com/joekiller/jruby-kafka/blob/master/lib/jruby-kafka/group.rb#L166

**Comment by joekiller** [comment]
So the consumer shouldn't need a custom serializer because you will get the message as it was when it was passed to the producer. When you consume the topic and pop the Kafka message you can do whatever you want with the message contents themselves so this wouldn't be needed.

Check out the docs here: http://kafka.apache.org/documentation.html#messages
